---
- name: Nginx Config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ paperless_ngx_docker_reverse_proxy_path }}/{{ nginx_config_file_name }}"
    owner: root
    group: root
    mode: "0640"

- name: Run Nginx proxy
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_reverse_proxy_container_name }}"
    image: "{{ paperless_ngx_docker_reverse_proxy_image }}"
    state: started
    restart_policy: unless-stopped
    pull: true
    networks: >-
      {{ omit
      if paperless_ngx_docker_dedicated_docker_network_name | length == 0
      else [{'name': paperless_ngx_docker_dedicated_docker_network_name}] }}
    ports:
      - "{{ paperless_ngx_docker_port }}:80"
    volumes:
      - "{{ paperless_ngx_docker_reverse_proxy_path }}/{{ nginx_config_file_name }}:/etc/nginx/nginx.conf"
