---
- name: Run Nginx proxy
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_reverse_proxy_container_name }}"
    image: "{{ paperless_ngx_docker_reverse_proxy_image }}"
    state: started
    restart_policy: unless-stopped
    pull: true
    networks: >-
      {{ omit
      if paperless_ngx_docker_dedicated_docker_network_name | length == 0
      else [{'name': paperless_ngx_docker_dedicated_docker_network_name}] }}
    ports:
      - "{{ paperless_ngx_docker_port }}:80"
