---
- name: Redis docker container absent
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_redis_container_name }}"
    state: absent

- name: DB container absent
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_db_container_name }}"
    state: absent

- name: Reverse proxy container absent
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_reverse_proxy_container_name }}"
    state: absent

- name: App container absent
  community.docker.docker_container:
    name: "{{ paperless_ngx_docker_app_container_name }}"
    state: absent

- name: Docker network absent
  community.docker.docker_network:
    name: "{{ paperless_ngx_docker_dedicated_docker_network_name }}"
    state: absent

- name: Config Directories absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ paperless_ngx_docker_reverse_proxy_path }}"
    - "{{ paperless_ngx_docker_redis_path }}"
    - "{{ paperless_ngx_docker_db_path }}"
    - "{{ paperless_ngx_docker_app_data_path }}"
    - "{{ paperless_ngx_docker_app_media_path }}"
    - "{{ paperless_ngx_docker_app_exort_path }}"
    - "{{ paperless_ngx_docker_app_consume_path }}"
    - "{{ paperless_ngx_docker_basedir }}"

- name: Ensure paperless user absent
  ansible.builtin.user:
    name: "{{ paperless_ngx_docker_user_host }}"
    state: absent

- name: Ensure group paperless-ngx absent
  ansible.builtin.group:
    name: "{{ paperless_ngx_docker_group_host }}"
    state: absent
