---
# defaults file for cnb2412.paperless-ngx-docker

paperless_ngx_docker_install: true

paperless_ngx_docker_basedir: "/opt/paperless-ngx"

# Docker config
paperless_ngx_docker_dedicated_docker_network_name: ""

# Redis config
paperless_ngx_docker_redis_image: docker.io/library/redis:7
paperless_ngx_docker_redis_container_name: "paperless-redis"
paperless_ngx_docker_redis_path: "{{ paperless_ngx_docker_basedir }}/redis"

# DB Config
paperless_ngx_docker_db_image: docker.io/library/postgres:latest
paperless_ngx_docker_db_container_name: "paperless-db"
paperless_ngx_docker_db_path: "{{ paperless_ngx_docker_basedir }}/database"
paperless_ngx_docker_db_name: "paperless"
paperless_ngx_docker_db_user: "paperless"
paperless_ngx_docker_db_password: "changeme"

# Reverse Proxy
paperless_ngx_docker_reverse_proxy_enable: false
paperless_ngx_docker_reverse_proxy_path: "{{ paperless_ngx_docker_basedir }}/nginx"
paperless_ngx_docker_reverse_proxy_container_name: "paperless-nginx"
paperless_ngx_docker_reverse_proxy_image: "docker.io/library/nginx:stable-alpine-slim"
paperless_ngx_docker_reverse_proxy_ssl_key: ""
paperless_ngx_docker_reverse_proxy_ssl_cert: ""

# App
paperless_ngx_docker_app_image: ghcr.io/paperless-ngx/paperless-ngx:latest
paperless_ngx_docker_app_container_name: paperless-ngx
paperless_ngx_docker_app_data_path: "{{ paperless_ngx_docker_basedir }}/data"
paperless_ngx_docker_app_media_path: "{{ paperless_ngx_docker_basedir }}/media"
paperless_ngx_docker_app_exort_path: "{{ paperless_ngx_docker_basedir }}/export"
paperless_ngx_docker_app_consume_path: "{{ paperless_ngx_docker_basedir }}/incomming"
paperless_ngx_docker_app_env_database_engine: "postgresql"
paperless_ngx_docker_app_secret_key: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname, length=60) }}"
paperless_ngx_docker_app_admin_user: "admin"
paperless_ngx_docker_app_admin_password: "admin"
paperless_ngx_docker_app_ocr_language: "eng"
paperless_ngx_docker_app_time_zone: "utc"
paperless_ngx_docker_app_url: ""
paperless_ngx_docker_app_csrf_trusted_origins: "{{ paperless_ngx_docker_app_url }}"
paperless_ngx_docker_app_use_x_forward_host: "{{ true if paperless_ngx_docker_reverse_proxy_enable else false }}"
paperless_ngx_docker_app_use_x_forward_port: "{{ true if paperless_ngx_docker_reverse_proxy_enable else false }}"
paperless_ngx_docker_app_enable_debug: false

# Generel config
paperless_ngx_docker_port: "8000"
